apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: java-ms-backstage-template
  title: Java Microservice
  description: create a new java microservice with springboot
spec:
  owner: backstage/techdocs-core
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Service Info
      required:
        - microserviceName
      properties:
        microserviceName:
          type: string
          title: Service Name
          description: Unique name for your service
        teamName:
          type: string
          title: Team Name
          description: Name of the team who owns this service
    - title: Features
      properties:
        features:
          title: Select Features
          type: array
          default: []
          items:
            type: string
            enum:
              - REST
              - Kafka
              - PostgreSQL
          uniqueItems: true
          ui:widget: checkboxes

  steps:
    - id: fetch-template
      name: Generate Java Code v4
      action: fetch:template
      input:
        url: https://github.com/jpereiramp/backstage-test/blob/main/templates/java-skeleton
        values:
          microserviceName: ${{ parameters.microserviceName }}
          features: ${{ parameters.features }}
    - id: fetch-template
      name: Generate K8s Code v4
      action: fetch:template
      input:
        url: https://github.com/jpereiramp/backstage-test/blob/main/templates/k8s-skeleton
        values:
          microserviceName: ${{ parameters.microserviceName }}
          teamName: ${{ parameters.teamName }}
          features: ${{ parameters.features }}
    - id: publish
      name: Publish to GitHub v4
      action: publish:github
      input:
        repoUrl: "github.com?repo=${{ parameters.microserviceName }}&owner=jpereiramp"
        description: Service ${{ parameters.microserviceName }} published via Backstage.
        repoVisibility: private
        token: ${{ secrets.githubToken }}
    - id: clean-empty-files
      name: Clean up empty files and folders
      action: shell:script
      input:
        workingDirectory: .
        script: |
          find . -type f -empty -delete
          find . -type d -empty -delete
  output:
    links:
      - title: Service Repository
        url: ${{ steps.publish.output.remoteUrl }}
