apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: java-ms-backstage-template
  title: Java Microservice v13
  description: Creates a new Java microservice with Springboot
spec:
  owner: best-team
  type: service
  parameters:
    - title: Service Info
      required:
        - microserviceName
      properties:
        microserviceName:
          type: string
          title: Service Name
          description: Unique name for your service
        teamName:
          type: string
          title: Team Name
          description: Name of the team who owns this service
    - title: Features
      properties:
        kafkaBoilerplate:
          title: Include Kafka Boilerplate
          type: boolean
          ui:widget: radio
        restBoilerplate:
          title: Include REST Boilerplate
          type: boolean
          ui:widget: radio
        postgresBoilerplate:
          title: Include Postgres Boilerplate
          type: boolean
          ui:widget: radio
  steps:
    - id: fetch-java
      name: Generate Java Code
      action: fetch:template
      input:
        url: https://github.com/jpereiramp/backstage-test/blob/main/templates/java-skeleton
        values:
          microserviceName: ${{ parameters.microserviceName }}
          teamName: ${{ parameters.teamName }}
          kafkaBoilerplate: ${{ parameters.kafkaBoilerplate }}
          restBoilerplate: ${{ parameters.restBoilerplate }}
          postgresBoilerplate: ${{ parameters.postgresBoilerplate }}
        templateFileExtension: .njk
    - id: fetch-k8s
      name: Generate K8s Code
      action: fetch:template
      input:
        url: https://github.com/jpereiramp/backstage-test/blob/main/templates/k8s-skeleton
        values:
          microserviceName: ${{ parameters.microserviceName }}
          teamName: ${{ parameters.teamName }}
          kafkaBoilerplate: ${{ parameters.kafkaBoilerplate }}
          restBoilerplate: ${{ parameters.restBoilerplate }}
          postgresBoilerplate: ${{ parameters.postgresBoilerplate }}
        templateFileExtension: .njk
    - id: delete-kafka
      if: ${{ not parameters.kafkaBoilerplate }}
      action: fs:delete
      input:
        files:
          - ./src/main/java/com/example/${{ parameters.microserviceName | lower | replace("-", "") }}/async
    - id: delete-rest
      if: ${{ not parameters.restBoilerplate }}
      action: fs:delete
      input:
        files:
          - ./src/main/java/com/example/${{ parameters.microserviceName | lower | replace("-", "") }}/rest
    - id: delete-postgres
      if: ${{ not parameters.postgresBoilerplate }}
      action: fs:delete
      input:
        files:
          - ./src/main/java/com/zwift/${{ parameters.microserviceName | lower | replace("-", "") }}/persistence
    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        repoUrl: "github.com?repo=${{ parameters.microserviceName }}&owner=jpereiramp"
        description: Service ${{ parameters.microserviceName }} published via Backstage.
        repoVisibility: private
        token: ${{ secrets.githubToken }}
  output:
    links:
      - title: Service Repository
        url: ${{ steps.publish.output.remoteUrl }}
