server:
  port: 8080
spring:
  application:
    name: ${{ values.microserviceName }}
{% if "Kafka" in values.features %}
  kafka:
    host: kafka:9092
{% endif %}
{% if "PostgreSQL" in values.features %}
  db:
    host: jdbc://my-db:5432/database
    user: test-user
    password: test-pwd
{% endif %}